
# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyein
tagline:          'A Jekyll theme'
description:      'Hello'
url:              http://hyeinyang.github.io
baseurl:          /

author:
  name:           'Hyein Yang'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
